version: "3"
volumes:
  dados:
networks:
  banco:
  web:
  fila:
services:
  db:
    image: postgres:9.6
    networks:
      - banco
    volumes:
      - dados:/var/lib/postgresql/data
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=<YourPass>
  frontend:
    image: nginx:1.13
    depends_on:
      - app
    networks:
      - web
    volumes:
      - ./web:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  app:
    image: python:3.6
    environment:
      - DB_NAME=email_sender
      - DB_PASS=<YourPass>
    networks:
      - banco
      - web
      - fila
    depends_on:
      - db
      - queue
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
  queue:
    image: redis:3.2
    networks:
      - fila
  worker:
    build: worker
    volumes:
      - ./worker:/worker
    working_dir: /worker
    command: worker.py
    networks:
      - fila
    depends_on:
      - queue
